- name: Distrobox build environment
  ansible.builtin.include_role:
    name: "{{ item}}"
  loop:
  - "{{ this }}/Distrobox"
  when: not in_Distrobox


- name: Install Dependencies
  ansible.builtin.include_role:
    name: "{{ this }}/depends"
  when: in_Distrobox

- name: Build CodeBlocks
  ansible.builtin.include_role:
    name: "{{ this }}/build"
  when: in_Distrobox and not debug
