---
# https://wiki.codeblocks.org/index.php/Installing_Code::Blocks_nightly_build_on_Ubuntu

- name: Install Dependencies
  ansible.builtin.apt:
    pkg:
    - build-essential
    - gdb
    - libwxgtk3.0-gtk3-0v5
    - libwxgtk3.0-gtk3-dev
  become: true

# new pkg names:
# https://packages.ubuntu.com/jammy/libwxgtk3.0-gtk3-0v5
# https://askubuntu.com/questions/1241217/package-libwxgtk3-0-dev-has-no-installation-candidate-on-ubuntu-20-04
# https://packages.ubuntu.com/jammy/libwxgtk3.0-gtk3-dev