---
# https://wiki.codeblocks.org/index.php/Installing_Code::Blocks_nightly_build_on_Ubuntu
- name: Install Dependencies
  ansible.builtin.apt:
    pkg:
    - build-essential
    - gdb
    - libwxgtk3.0
    - libwxgtk3.0-gtk3-dev
  become: true
  when: repository


# missing:
# https://askubuntu.com/questions/1241217/package-libwxgtk3-0-dev-has-no-installation-candidate-on-ubuntu-20-04
# https://packages.ubuntu.com/search?keywords=libwxgtk3.0-gtk3-dev
