---
- name: Install CodeBlocks & Clangd Language Server
  hosts: localhost # , node
  vars:
    build_from_source: false
    # compiler: Clang
    rerun_ansible_in_container: true

  roles:
  # - language server/Clangd
    - in Distrobox
    - Code Blocks

# The package in repositories too old to use Clangd. If you want to use latest Clangd Language Server: you have to build from source.
