---
- hosts: localhost #, node
  vars:
    compiler: "GNU C++"

  roles:
  - language server/Clangd
  - Code Blocks

# The package in repositories too old to use Clangd. If you want to use latest Clangd code completion? You have to build from source.